services:
  # Backend API Service
  - type: web
    name: marketmesh-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # Set this in Render Dashboard with your MongoDB Atlas connection string
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /

  # Frontend Static Site
  - type: web
    name: marketmesh-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend-angular && npm install && npm run build
    staticPublishPath: frontend-angular/dist/frontend-angular/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
